name: Build Node.js
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NODE_VERSION: "23.8.0"
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - { os: ubuntu-20.04, name: linux-x64 }
          - { os: ubuntu-22.04-arm, name: linux-arm64 }
          - { os: macos-13, name: darwin-x64 }
          - { os: macos-latest, name: darwin-arm64 }
          - { os: windows-latest, name: win32-x64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nodejs/node
          ref: v${{ env.NODE_VERSION }}
      - if: runner.os == 'Windows'
        run: ./vcbuild.bat dll
      - if: runner.os != 'Windows'
        run: ./configure --shared && make -j$(nproc)
      - uses: actions/upload-artifact@v4
        with:
          name: node-${{ matrix.name }}
          path: out/Release
