name: Build Node.js
on:
  workflow_dispatch:
  workflow_call:
jobs:
  node-version:
    outputs:
      node-version: ${{ steps.node-version.outputs.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: node-version
        run: |
          node_version=$(cat VERSION | grep -Po '\d+\.\d+\.\d+')
          echo "node-version=$node_version" >> "$GITHUB_OUTPUT"
  build:
    needs: node-version
    strategy:
      fail-fast: true
      matrix:
        include:
          - { os: ubuntu-22.04, name: linux-x64 }
          - { os: ubuntu-22.04-arm, name: linux-arm64 }
          - { os: macos-13, name: darwin-x64 }
          - { os: macos-14, name: darwin-arm64 }
          - { os: windows-2022, name: win32-x64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nodejs/node
          ref: v${{ needs.node-version.outputs.node-version }}
      - if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - if: runner.os == 'Windows'
        run: ./vcbuild.bat dll
      - if: runner.os == 'macOS'
        run: ./configure --shared && make -j$(sysctl -n hw.logicalcpu)
      - if: runner.os == 'Linux'
        run: ./configure --shared && make -j$(nproc)
      - uses: actions/upload-artifact@v4
        with:
          name: node-v${{ needs.node-version.outputs.node-version }}-${{ matrix.name }}
          path: |
            out/Release/libnode.*
            out/Release/node.*
            out/Release/node
