name: Create release
on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
jobs:
  build:
    uses: ./.github/workflows/build.yml
  version:
    outputs:
      version: ${{ steps.version.outputs.version }}
      prerelease: ${{ steps.version.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: version
        run: |
          version=$(cat VERSION)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          if [[ $(echo "$version") == $(echo "$version" | grep -Po '\d+\.\d+\.\d+') ]]; then
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          fi
  release:
    needs: [build, version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-linux-x64
      - run: (cd node-linux-x64 && ln libnode.so.* libnode.so)
      - run: tar czf ./node-linux-x64.tar.gz ./node-linux-x64 && rm -rf ./node-linux-x64
      - uses: actions/download-artifact@v4
        with:
          name: node-linux-arm64
      - run: tar czf ./node-linux-arm64.tar.gz ./node-linux-arm64 && rm -rf ./node-linux-arm64
      - uses: actions/download-artifact@v4
        with:
          name: node-darwin-x64
      - run: tar czf ./node-darwin-x64.tar.gz ./node-darwin-x64 && rm -rf ./node-darwin-x64
      - uses: actions/download-artifact@v4
        with:
          name: node-darwin-arm64
      - run: tar czf ./node-darwin-arm64.tar.gz ./node-darwin-arm64 && rm -rf ./node-darwin-arm64
      - uses: actions/download-artifact@v4
        with:
          name: node-win32-x64
      - run: zip -r ./node-win32-x64.zip ./node-win32-x64 && rm -rf ./node-win32-x64
      - env:
          version: ${{ needs.version.outputs.version }}
        run: gh release create "v$version" --generate-notes ${{ needs.version.outputs.prerelease && '--prerelease' || '' }} ${{ inputs.draft && '--draft' || '' }} ./node-linux-x64.tar.gz ./node-linux-arm64.tar.gz ./node-darwin-x64.tar.gz ./node-darwin-arm64.tar.gz ./node-win32-x64.zip
